# Generated by Django 5.2.4 on 2025-07-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('bio', models.TextField(max_length=2047)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=127)),
                ('birthDate', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('password', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=1, max_digits=4)),
                ('is_stuff', models.BooleanField()),
                ('gender', models.CharField(choices=[('1', 'دختر'), ('2', 'پسر')], max_length=1)),
                ('experience', models.CharField(choices=[('0', 'مقدماتی'), ('1', 'متوسط'), ('2', 'پیشرفته')], max_length=1)),
            ],
        ),
    ]
