# Generated by Django 5.2.4 on 2025-07-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ به روز رسانی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(null=True, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, max_length=2047, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthDate',
            field=models.DateField(null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=127, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='person',
            name='experience',
            field=models.CharField(choices=[('0', 'مقدماتی'), ('1', 'متوسط'), ('2', 'پیشرفته')], max_length=1, null=True, verbose_name='سطح تجربه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=127, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('1', 'دختر'), ('2', 'پسر')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='قد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_stuff',
            field=models.BooleanField(verbose_name='وضعیت کارمندی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=127, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=20, null=True, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=13, null=True, verbose_name='شماره تلفن'),
        ),
    ]
