# Generated by Django 5.2.4 on 2025-07-26 17:25

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_person_updated_at_alter_person_age_alter_person_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='jalali_date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
