# Generated by Django 5.2.4 on 2025-07-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readers',
            field=models.ManyToManyField(related_name='readed_blogs', to='base.person'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='base.person'),
        ),
    ]
