# Generated by Django 5.2.4 on 2025-08-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_blog_readers_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='readed_blogs', to='base.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
